import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = (process.argv[2] === 'production');
const outdir = '../opensidian_release';

// Ensure output directory exists
if (!fs.existsSync(outdir)) {
	fs.mkdirSync(outdir, { recursive: true });
	console.log(`Created output directory: ${outdir}`);
}

// Copy manifest.json and other files to output directory
function copyFiles() {
	const filesToCopy = ['manifest.json', 'styles.css'];
	for (const file of filesToCopy) {
		const src = path.join(__dirname, file);
		const dest = path.join(outdir, file);
		if (fs.existsSync(src)) {
			fs.copyFileSync(src, dest);
			console.log(`Copied ${file} to ${outdir}`);
		}
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/*',
		'lezer',
		'@lezer/*',
		...builtins],
	format: 'cjs',
	target: 'es2022',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: path.join(outdir, 'main.js'),
	minify: prod,
	platform: 'node',
	define: {
	'process.env.NODE_ENV': prod ? '"production"' : '"development"'
	},
	mainFields: ['main', 'module'],
	conditions: ['require', 'node']
});

if (prod) {
	await context.rebuild();
	copyFiles();
	console.log(`Build complete. Output: ${path.join(outdir, 'main.js')}`);
	process.exit(0);
} else {
	await context.watch();
}
